import { defineNuxtConfig } from "nuxt/config"

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2026-09-29",
  devtools: { enabled: true },
  modules: [
    "@nuxt/ui",
    "@nuxt/test-utils/module",
    "@nuxt/eslint",
    "nuxt-security",
    "@nuxtjs/seo",
    "@nuxt/scripts",
    "@nuxt/fonts",
  ],
  css: ["~/assets/css/main.css"],
  runtimeConfig: {
    public: {
      appVersion: process.env.npm_package_version || "unknown",
      contactFormToEmail: "benoit@frites.dev",
      emailjsUserPubKey: "v_5w2uNf_muKtiZ_h",
      emailjsServiceId: "service_eqtnwg3",
      emailjsTemplateId: "template_grzi0mc",
      captchaSiteKey: "6Le_eE8qAAAAAPsyNWtWJZTulFsdQ98bOM2KiC3w",
    },
  },
  ui: {
    // The site is dark only
    colorMode: false,
  },
  fonts: {
    families: [
      {
        name: "Montserrat",
        provider: "google",
        weights: [400, 500, 600, 700],
        styles: ["normal"],
        // Required by nuxt-og-image to render the font in OG images
        global: true,
      },
    ],
  },
  icon: {
    // The site is statically generated: icons must be bundled, there is no icon server
    clientBundle: {
      scan: { globInclude: ["app/**/*.{vue,ts}"] },
      sizeLimitKb: 512,
    },
    fallbackToApi: false,
  },
  ogImage: {
    zeroRuntime: true,
  },
  site: {
    url: "https://frites.dev",
    name: "frites.dev SRL • Tailored Software Solutions",
    description:
      "frites.dev SRL is a software development company providing tailored solutions for businesses.",
    defaultLocale: "en",
  },
  schemaOrg: {
    identity: "Organization",
  },
  app: {
    head: {
      htmlAttrs: { class: "dark" },
      // Other meta items (title, locale, description) are auto-generated by NuxtSEO
      meta: [
        { charset: "utf-8" },
        { name: "theme-color", content: "#0a0a0a" },
        {
          name: "viewport",
          content: "width=device-width, height=device-height, initial-scale=1",
        },
      ],
      // icon link items are auto-generated by NuxtSEO
      link: [{ rel: "manifest", href: "/site.webmanifest" }],
    },
  },
  security: {
    headers: {
      crossOriginEmbedderPolicy:
        process.env.NODE_ENV === "development" ? "unsafe-none" : "require-corp", //https://github.com/Baroshem/nuxt-security/issues/101
      contentSecurityPolicy: {
        "upgrade-insecure-requests": process.env.NODE_ENV === "development" ? false : true, // USE ONLY IN DEV MODE
      },
    },
    corsHandler: {
      origin: "*",
    },
  },
  typescript: {
    typeCheck: "build",
    // *.spec.ts test app code (app aliases), *.test.ts test the Nuxt config (node types)
    tsConfig: {
      include: ["../tests/**/*.spec.ts"],
    },
    nodeTsConfig: {
      include: ["../tests/**/*.test.ts"],
    },
  },
})
